repo_url: https://T-R-A-V-A-Z-A-P.github.io/fdroid-repo/repo
repo_name: Shared Apps F-Droid Repo
repo_description: Shared binary F-Droid repository for multiple Android apps.
repo_icon: fdroid-icon.png
archive_older: 0
make_current_version_link: false
